"""Created: 2026-09-27

Purpose: Persists complete Wormhole conversations with model-generated meaning.

Every successful Chat turn is stored in one human-readable JSON document per
conversation.  Deterministic code records technical provenance and performs
atomic persistence; Gemma alone supplies semantic summaries, topics, goals,
decisions, opportunities, and follow-up suggestions.  A failed semantic pass
never invents replacement tags: the full turn is still captured and marked for
later analysis.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from threading import RLock
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from easy_agents.constellation.commons_runtime import VaultId
from easy_agents.galaxy.identity import Identifier


_IDENTIFIER_PATTERN = re.compile(r"^[a-z][a-z0-9_.-]{0,127}$")


class _JournalModel(BaseModel):
    """Strict immutable base for journal records and model outputs."""

    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)


class ConversationAnalysis(_JournalModel):
    """Semantic interpretation generated by Gemma for one conversation turn."""

    analysis_id: Identifier
    summary: str = Field(min_length=8, max_length=1_500)
    primary_intent: str = Field(min_length=2, max_length=240)
    topics: tuple[str, ...] = Field(default=(), max_length=12)
    tags: tuple[str, ...] = Field(default=(), max_length=16)
    user_goals: tuple[str, ...] = Field(default=(), max_length=10)
    named_entities: tuple[str, ...] = Field(default=(), max_length=12)
    facts_to_remember: tuple[str, ...] = Field(default=(), max_length=10)
    decisions: tuple[str, ...] = Field(default=(), max_length=10)
    opportunities: tuple[str, ...] = Field(default=(), max_length=10)
    constraints_or_risks: tuple[str, ...] = Field(default=(), max_length=10)
    open_questions: tuple[str, ...] = Field(default=(), max_length=10)
    suggested_follow_ups: tuple[str, ...] = Field(default=(), max_length=10)
    relevance: Literal["routine", "useful", "important", "strategic"]
    sensitivity: Literal["ordinary", "personal", "confidential", "sensitive"]


class ConversationReview(_JournalModel):
    """Model-generated cross-turn review of a captured exploration."""

    review_id: Identifier
    created_at: datetime
    summary: str = Field(min_length=8, max_length=2_000)
    recurring_themes: tuple[str, ...] = Field(default=(), max_length=12)
    direction_of_travel: tuple[str, ...] = Field(default=(), max_length=10)
    decisions_and_commitments: tuple[str, ...] = Field(default=(), max_length=12)
    promising_opportunities: tuple[str, ...] = Field(default=(), max_length=12)
    unresolved_questions: tuple[str, ...] = Field(default=(), max_length=12)
    recommended_next_steps: tuple[str, ...] = Field(default=(), max_length=12)
    knowledge_worth_preserving: tuple[str, ...] = Field(default=(), max_length=12)


class JournalTurn(_JournalModel):
    """One fully captured user/assistant exchange and its route provenance."""

    message_id: Identifier
    mission_id: Identifier
    created_at: datetime
    user_message: str
    assistant_message: str
    vault_id: VaultId
    duration_ms: float = Field(ge=0)
    circle_ids: tuple[str, ...]
    planet_ids: tuple[str, ...]
    invoked_satellite_ids: tuple[str, ...] = ()
    answer_source: str
    analysis_status: Literal["captured", "pending"]
    analysis: ConversationAnalysis | None = None
    analysis_error: str | None = None


class ConversationJournalRecord(_JournalModel):
    """Durable JSON document for one Wormhole conversation."""

    version: Literal[1] = 1
    conversation_id: Identifier
    galaxy_id: str
    created_at: datetime
    updated_at: datetime
    turns: tuple[JournalTurn, ...]
    latest_review: ConversationReview | None = None


class JournalCaptureEvidence(_JournalModel):
    """Small journal receipt returned to Chat and rendered in the UI."""

    conversation_id: Identifier
    status: Literal["captured", "pending"]
    turn_count: int = Field(ge=1)
    updated_at: datetime
    analysis_id: Identifier | None = None
    summary: str | None = None
    tags: tuple[str, ...] = ()


class ConversationJournal:
    """Atomic per-conversation JSON storage with model-only semantic analysis.

    Args:
        directory: Private local directory containing one JSON file per
            conversation.  Files are named only from validated conversation IDs.
        llm: Local Gemma-compatible client.  ``structured_generate`` is required
            for semantic tagging and reviews; technical capture still works when
            it is temporarily unavailable.
        galaxy_id: Stable owner recorded in each journal.
    """

    def __init__(self, directory: Path, *, llm: Any, galaxy_id: str = "personal") -> None:
        self.directory = Path(directory)
        self.directory.mkdir(parents=True, exist_ok=True)
        self.llm = llm
        self.galaxy_id = galaxy_id
        self._lock = RLock()
        self._model_lock = RLock()

    def capture(
        self,
        *,
        conversation_id: Identifier,
        message_id: Identifier,
        mission_id: Identifier,
        user_message: str,
        assistant_message: str,
        vault_id: VaultId,
        duration_ms: float,
        circle_ids: tuple[str, ...],
        planet_ids: tuple[str, ...],
        invoked_satellite_ids: tuple[str, ...],
        answer_source: str,
    ) -> JournalCaptureEvidence:
        """Captures a complete turn before post-response semantic analysis.

        The immediate record is marked ``pending``. The API calls
        :meth:`analyze_turn` after sending the Chat response, so slow local
        inference does not delay the answer or its completed timing.
        """

        with self._lock:
            existing = self._read_optional(conversation_id)
            now = datetime.now(UTC)
            turn = JournalTurn(
                message_id=message_id,
                mission_id=mission_id,
                created_at=now,
                user_message=user_message,
                assistant_message=assistant_message,
                vault_id=vault_id,
                duration_ms=round(duration_ms, 3),
                circle_ids=circle_ids,
                planet_ids=planet_ids,
                invoked_satellite_ids=invoked_satellite_ids,
                answer_source=answer_source,
                analysis_status="pending",
                analysis=None,
                analysis_error=None,
            )
            record = ConversationJournalRecord(
                conversation_id=conversation_id,
                galaxy_id=self.galaxy_id,
                created_at=existing.created_at if existing else now,
                updated_at=now,
                turns=(*existing.turns, turn) if existing else (turn,),
                latest_review=existing.latest_review if existing else None,
            )
            self._write(record)
            return JournalCaptureEvidence(
                conversation_id=conversation_id,
                status="pending",
                turn_count=len(record.turns),
                updated_at=now,
                analysis_id=None,
                summary=None,
                tags=(),
            )

    def analyze_turn(
        self,
        conversation_id: Identifier,
        message_id: Identifier,
    ) -> JournalCaptureEvidence:
        """Generates model-only semantics for one pending captured turn.

        Model calls are serialized for the single local Gemma service while
        journal reads remain available. Failed analysis remains visibly pending
        with a bounded diagnostic; code never fabricates semantic metadata.
        """

        with self._lock:
            snapshot = self.get(conversation_id)
            target = next(
                (item for item in snapshot.turns if item.message_id == message_id),
                None,
            )
            if target is None:
                raise KeyError(f"Unknown journal message: {message_id}")
            if target.analysis is not None:
                return self._evidence(snapshot, target)
        with self._model_lock:
            analysis, error = self._analyze_turn(
                user_message=target.user_message,
                assistant_message=target.assistant_message,
                previous=snapshot,
            )
        with self._lock:
            latest = self.get(conversation_id)
            updated_turns = tuple(
                item.model_copy(
                    update={
                        "analysis_status": "captured" if analysis else "pending",
                        "analysis": analysis,
                        "analysis_error": error,
                    }
                )
                if item.message_id == message_id
                else item
                for item in latest.turns
            )
            updated = latest.model_copy(
                update={"updated_at": datetime.now(UTC), "turns": updated_turns}
            )
            self._write(updated)
            final_turn = next(
                item for item in updated.turns if item.message_id == message_id
            )
            return self._evidence(updated, final_turn)

    def get(self, conversation_id: Identifier) -> ConversationJournalRecord:
        """Returns one journal or raises ``KeyError`` when it does not exist."""

        with self._lock:
            record = self._read_optional(conversation_id)
            if record is None:
                raise KeyError(f"Unknown conversation journal: {conversation_id}")
            return record

    def list(self) -> tuple[ConversationJournalRecord, ...]:
        """Lists journals with newest activity first."""

        with self._lock:
            records = [
                ConversationJournalRecord.model_validate_json(path.read_text(encoding="utf-8"))
                for path in self.directory.glob("*.json")
                if path.is_file()
            ]
        return tuple(sorted(records, key=lambda item: item.updated_at, reverse=True))

    def review(self, conversation_id: Identifier) -> ConversationReview:
        """Asks Gemma for a cross-turn review and persists the validated result."""

        with self._lock:
            record = self.get(conversation_id)
        generate = getattr(self.llm, "structured_generate", None)
        if not callable(generate):
            raise RuntimeError("Gemma structured generation is unavailable for review.")
        transcript = [
            {
                "user": turn.user_message,
                "assistant": turn.assistant_message,
                "analysis": (
                    turn.analysis.model_dump(mode="json") if turn.analysis else None
                ),
            }
            for turn in record.turns
        ]
        prompt = f"""Review this private local conversation as a thoughtful exploration aide.
Identify themes, direction, decisions, promising opportunities, unresolved questions,
next steps, and durable knowledge. Use only supplied text. Do not invent commitments.
Use at most three short items per array and at most twelve words per item.
Return a JSON object matching the requested schema. Set review_id to
\"review-{uuid4().hex}\" and created_at to \"{datetime.now(UTC).isoformat()}\".

Conversation JSON:
{json.dumps(transcript, ensure_ascii=False, default=str)}"""
        with self._model_lock:
            review = self._generate_structured(
                prompt=prompt,
                schema=ConversationReview,
                label="conversation review",
                max_tokens=768,
            )
        with self._lock:
            latest = self.get(conversation_id)
            updated = latest.model_copy(
                update={"updated_at": datetime.now(UTC), "latest_review": review}
            )
            self._write(updated)
            return review

    def delete(self, conversation_id: Identifier) -> bool:
        """Deletes one journal explicitly and reports whether a file existed."""

        with self._lock:
            path = self._path(conversation_id)
            if not path.exists():
                return False
            path.unlink()
            return True

    def _analyze_turn(
        self,
        *,
        user_message: str,
        assistant_message: str,
        previous: ConversationJournalRecord | None,
    ) -> tuple[ConversationAnalysis | None, str | None]:
        """Returns Gemma semantics or a bounded diagnostic with no invented tags."""

        generate = getattr(self.llm, "structured_generate", None)
        if not callable(generate):
            return None, "Gemma structured generation is unavailable; semantic analysis is pending."
        previous_summaries = [
            turn.analysis.summary
            for turn in (previous.turns[-5:] if previous else ())
            if turn.analysis is not None
        ]
        analysis_id = f"analysis-{uuid4().hex}"
        prompt = f"""Tag one private local assistant conversation turn for future review.
Use only the supplied messages. Extract concrete topics, goals, named entities, facts,
decisions, opportunities, constraints, questions, and useful follow-ups. Prefer short,
specific tags. Do not infer sensitive attributes that the user did not state. Empty
categories must be empty arrays. Use at most three short items per array and at most
eight words per item. Return JSON matching the requested schema and set
analysis_id to \"{analysis_id}\".

Previous turn summaries: {json.dumps(previous_summaries, ensure_ascii=False)}
User message: {user_message}
Assistant response: {assistant_message}"""
        try:
            return (
                self._generate_structured(
                    prompt=prompt,
                    schema=ConversationAnalysis,
                    label="conversation analysis",
                    max_tokens=640,
                ),
                None,
            )
        except (TypeError, ValueError) as exc:
            return None, f"{type(exc).__name__}: {exc}"[:800]

    def _generate_structured(
        self,
        *,
        prompt: str,
        schema: type[_JournalModel],
        label: str,
        max_attempts: int = 2,
        max_tokens: int = 512,
    ) -> Any:
        """Retries invalid semantic output through Gemma without rule fallback."""

        generate = getattr(self.llm, "structured_generate")
        correction = ""
        for attempt in range(1, max_attempts + 1):
            try:
                value = generate(
                    f"{prompt}{correction}",
                    schema,
                    max_tokens=max_tokens,
                )
                return value if isinstance(value, schema) else schema.model_validate(value)
            except (TypeError, ValueError, ValidationError) as exc:
                if attempt == max_attempts:
                    raise
                correction = (
                    f"\n\nThe previous {label} JSON was invalid. Return only a corrected "
                    f"object. Validation feedback: {type(exc).__name__}: {exc}"[:1_000]
                )
        raise AssertionError("unreachable structured generation loop")

    @staticmethod
    def _evidence(
        record: ConversationJournalRecord,
        turn: JournalTurn,
    ) -> JournalCaptureEvidence:
        """Projects one stored turn into the small Chat/UI journal receipt."""

        analysis = turn.analysis
        return JournalCaptureEvidence(
            conversation_id=record.conversation_id,
            status=turn.analysis_status,
            turn_count=len(record.turns),
            updated_at=record.updated_at,
            analysis_id=analysis.analysis_id if analysis else None,
            summary=analysis.summary if analysis else None,
            tags=analysis.tags if analysis else (),
        )

    def _path(self, conversation_id: Identifier) -> Path:
        """Maps an already validated identifier to its private journal file."""

        if not _IDENTIFIER_PATTERN.fullmatch(conversation_id):
            raise ValueError("Conversation journal identifier is invalid.")
        return self.directory / f"{conversation_id}.json"

    def _read_optional(
        self, conversation_id: Identifier
    ) -> ConversationJournalRecord | None:
        path = self._path(conversation_id)
        if not path.exists():
            return None
        return ConversationJournalRecord.model_validate_json(
            path.read_text(encoding="utf-8")
        )

    def _write(self, record: ConversationJournalRecord) -> None:
        """Atomically replaces one formatted JSON journal."""

        path = self._path(record.conversation_id)
        temporary = path.with_suffix(".json.tmp")
        temporary.write_text(
            json.dumps(
                record.model_dump(mode="json"),
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
                default=str,
            )
            + "\n",
            encoding="utf-8",
        )
        temporary.replace(path)
